<div id="slide"><?php include(TEMPLATEPATH."/lang.php"); ?><div id="sliderutama"><div id="foo2"><?php $idcat = get_option('nt_catid');$catnum = get_option('nt_catnum');$kat='numberposts='.$catnum.'&cat='.$idcat;?>
<?php $cat_posts = get_posts($kat);
foreach( $cat_posts as $post ) :
setup_postdata($post);
?>
<?php $getu=get_bloginfo('template_url');$postingan = get_option('nt_post');$get_gambar = get_the_content();$gamb=explode("src=\"",$get_gambar,2);$gamba=explode("\"",$gamb[1],2);$get_gambar1 = str_replace("SL160","SS180",$get_gambar);$gamb1=explode("http://ecx",$get_gambar1,2);$gamba1=explode("\"",$gamb1[1],2);if ($gamba[0]==TRUE) {$gambare = $gamba[0];}else{$gambare=$getu.'/images/noimage.jpg';}$gambar1 = 'http://ecx'.$gamba1[0];$gambarwpz = get_post_meta($post->ID, 'amzn_MediumImageURL', $single = true);$gambarwpz=str_replace("SL160","SS180",$gambarwpz);$gambarasg = get_post_meta($post->ID, 'amazon-image-url', $single = true);$gambarasg=str_replace("SL160","SS180",$gambarasg);$gambarwpr1 = get_post_meta($post->ID, 'image', $single = true);$gambarwpr1=str_replace("SL160","SS180",$gambarwpr1);$gambarwpr1=str_replace("SL300","SS180",$gambarwpr1);$gambarwpr2 = get_post_meta($post->ID, 'thumb', $single = true);$gambarwpr2=str_replace("SL160","SS180",$gambarwpr2);$gambarwpr2=str_replace("SL300","SS180",$gambarwpr2);$image = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'single-post-thumbnail' );$gmb=$image[0];?>


<div id="slider"><a href="<?php the_permalink() ?>" title="<?php the_title(); ?>" rel="bookmark"><img src="<?php if ($gambarwpz == TRUE) {echo $gambarwpz;} elseif ($gambarasg == TRUE) {echo $gambarasg;}elseif($gambarwpr1 == TRUE) {echo $gambarwpr1;}elseif($gamba1[0] == TRUE) {echo $gambar1;} elseif($gambarwpr2 == TRUE) {echo $gambarwpr2;} else{echo $getu.'/thumb.php?w=180&h=180&zc=2&src='.$gmb;}?>" style="height:180px; width:180px;float:left;margin-right:20px;" alt="<?php the_title(); ?>"/></a><h2 class="title"><a href="<?php the_permalink() ?>" title="<?php the_title(); ?>" rel="bookmark"><?php $the_title = $post->post_title;  $getlength = strlen($the_title); $thelength = 40; echo substr($the_title, 0, $thelength); if ($getlength > $thelength) ; ?>.</a></h2>Posted by <u><a href="<?php the_author_link();?>"><?php the_author();?></a></u>  in <u><?php the_category(', ');?></u><p><?php $det = get_post_meta($post->ID, 'amzn_ProductDescription', $single = true);$dapatpanjang = strlen($det); $panjang = 200; $detik = substr($det, 0, $panjang);?><?php if ($det==TRUE){echo strip_tags($detik);}else{echo '';}?></p><?php the_excerpt();?><a href="<?php the_permalink();?>" style="color:#fff"><span class="selengkapnya"><?php $vdt=get_option('nt_vdt');if ($vdt==TRUE){echo $vdt;} else {echo $lang[9];}?> &raquo;</span></a></div><?php endforeach; ?></div><div class="featribbon"></div><a id="next2" href="#" style="color:#fff"><span class="tom2">&rsaquo;</span></a><a id="prev2" href="#" style="color:#fff"><span class="tom1">&lsaquo;</span></a><br style="clear:both"></div>

<?php $kodeiklan=get_option('nt_addis');$kodeiklan=str_replace('\\','',$kodeiklan);$disf=get_option('nt_discount');if ($disf=='ad banner') {echo '<div id="pencarian">'.$kodeiklan.'</div>';}else {include(TEMPLATEPATH."/mencari.php");} ?><div style="clear:both"></div></div>